### ISSUE TITLE
Add tokenization algorithms

### ISSUE THREAD

**Issue by LBenzahia** [kariminf/jslingua#15]
- [ ] We'll inspire them from [nltk tokenzations ](https://github.com/nltk/nltk/tree/develop/nltk/tokenize)

**Comment by kariminf** [comment]
Tokenization is a scheduled for Syntax module 

The intended modules:
* Info
* Lang
* Morpho
* Syntax (sentence segmentation, word tokenization, stop word removal, etc.)
* Semantic (I don't think it is possible to include such functions)

**Comment by LBenzahia** [comment]
I agree, I like the idea :100:

**Comment by kariminf** [comment]
I think tokenization is a morphology task. So, it should be implemnted  in Morpho.

**Comment by kariminf** [comment]
The tokenization has been added to Morpho; but not the language implimentations
