### ISSUE TITLE
newStemmer method 

### ISSUE THREAD

**Issue by LBenzahia** [kariminf/jslingua#34]
https://github.com/kariminf/jslingua/blob/f0e011d8ce716df4abeb5f2ee6d27a9a1688581b/morpho.js#L319

When i create  a new stemmer and recreate second one the second crushed the 1st stemmer 
```js
    Morpho.newStemmer.call(this, "porterStemmer", "English proter stemmr", porterStemmer);
    Morpho.newStemmer.call(this, "lancasterStemmer", "English Lnacaster stemmer", lancasterStemmer);
```
How to add new stemmer to English Morpho module without crushed previous stemmers ?
you'll find the code in #35

**Comment by kariminf** [comment]
There is no problem in the function; it preserves all functions. The problem is in the test unit. See my comment there #35
