### ISSUE TITLE
how to use Morpho.Feature.POS

### ISSUE THREAD

**Issue by turnono** [kariminf/jslingua#36]
Hi, i would like to use Morpho.Feature.POS but I am not sure how to implement it. Could someone please point me in the right direction?

**Comment by kariminf** [comment]
Hi, 
I didn't really understand your question. Anyway, you can see Morpho.Feature.POS as an enum. class enumerating different part of speech. 
The feature will be used for a function not declared yet in Morpho.js which is the transformation from a POS to another such as [Nominalization](https://en.wikipedia.org/wiki/Nominalization)
