### ISSUE TITLE
English conj bug with words starting with "re"

### ISSUE THREAD

**Issue by martinchristov** [kariminf/jslingua#57]
remain -> becomes "main" in the past. "I mained"
request -> "I quested"
return -> "I turned"
---
Also:
finish -> "I inish", "I inished"

**Comment by kariminf** [comment]
Actually, it is remained, returned, etc.

https://conjugator.reverso.net/conjugation-english-verb-remain.html

**Comment by martinchristov** [comment]
Salam. You must have misunderstood me. Yes "remain" correctly becomes "remained", but in your conjugator it becomes "mained".
https://www.dropbox.com/s/rwf5b49434l1goa/Screenshot%202020-05-17%2016.40.27.png?dl=0

Sorry for not being more clear

**Comment by kariminf** [comment]
Salam, 
Sorry, I misunderstood  the issue. 
Thank you for reporting. 
It will be fixed ASAP

**Comment by kariminf** [comment]
The problem has been fixed (here and in jslingua.web)
The package will be fixed in the next release
Thank you for reporting
