### ISSUE TITLE
Eng conj "can" becomes "canned" instead of "could" in the past

### ISSUE THREAD

**Issue by martinchristov** [kariminf/jslingua#58]

**Comment by kariminf** [comment]
There are two verbs "can" 
- can : which means "able to". The past is "could"
- can: which means "put in a can". The past is "canned" 

The first one is more used and known than the last; this is why we chose to use it instead 
https://www.merriam-webster.com/dictionary/can

**Comment by martinchristov** [comment]
Salam. In your conjugator "can" becomes "canned" instead of "could".
So I'm not sure what you mean by saying that you have chosen the more popular meaning.

**Comment by kariminf** [comment]
Salam, 
Apparently, I changed something in the code which led to this issue. 
Thank you for reporting. 
The issue will be fixed ASAP

**Comment by kariminf** [comment]
The problem has been fixed (here and in jslingua.web)
The package will be fixed in the next release
Thank you for reporting
