### ISSUE TITLE
Japanese conjugation forms issue

### ISSUE THREAD

**Issue by shilik** [kariminf/jslingua#64]
Hi, @kariminf 
I use the following codes to get a designated verb form. but returns nothing.
Is there anything wrong with the codes?

` const jpnForms =jpnMorpho.lform();
      const verb = "食べる";
      console.log("Object.assign",Object.assign({},jpnForms["pres"]));
       let conjugation_form=jpnMorpho.conj(verb,Object.assign({},jpnForms["pres"]));
       console.log("present form",conjugation_form);`

**Comment by kariminf** [comment]
You have to add the formality level. Maybe, in the next version, I will define a default formality.

The formality is either: "plain" or "polite"

Here the code:

```
const JsLingua = require('jslingua');
const jpnMorpho = JsLingua.gserv('morpho', 'jpn');
const jpnForms =jpnMorpho.lform();
let verb = "食べる";

const conjopt = Object.assign({formality: "plain"},jpnForms["pres"]);

console.log("Object.assign", conjopt);
let conjugation_form=jpnMorpho.conj(verb, conjopt);
console.log("present form",conjugation_form);
```

**Comment by shilik** [comment]
Hi, @kariminf

As I simply used the code snippets in your examples for English which lacks the property of "formality" in Japanese. You are right. It would be better to add default "formality" property in the pre-defined forms.  Thank you!
